
/* 1 задача */

SELECT TOP 1 NAME FROM EMPLOYEE
ORDER BY SALARY DESC

/* 2 задача */

;WITH DEPTH_CTE (ID,CHIEF_ID,DEPTH)
 AS
 (
	SELECT ID, CHIEF_ID, 1 AS DEPTH FROM EMPLOYEE
	WHERE CHIEF_ID IS NULL
	UNION ALL
	SELECT E.ID, E.CHIEF_ID, C.DEPTH+1 AS DEPTH
	FROM EMPLOYEE E 
	JOIN DEPTH_CTE C ON E.CHIEF_ID=C.ID
 )
SELECT MAX(DEPTH) AS DEPTH FROM DEPTH_CTE 

/* 3 задача */

SELECT NAME FROM DEPARTMENT 
WHERE ID=(SELECT TOP 1 DEPARTMENT_ID FROM EMPLOYEE
			GROUP BY DEPARTMENT_ID
			ORDER BY SUM(SALARY) DESC)

/* 4 задача */

SELECT NAME FROM EMPLOYEE
WHERE NAME LIKE N'Р%н'

